# Generated by Django 4.1.2 on 2022-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('lang', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expired_on', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
