# Generated by Django 4.1.2 on 2022-11-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='user_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
